# Generated by Django 6.0.2 on 2026-05-16 16:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(max_length=50)),
                ('departments', models.ManyToManyField(related_name='instructors', to='accounts.department')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(max_length=10, unique=True)),
                ('lesson_name', models.CharField(max_length=100)),
                ('credit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Invalid Credit'), django.core.validators.MaxValueValidator(4, message='Invalid Credit')])),
                ('active_credit', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0, message='Invalid Credit'), django.core.validators.MaxValueValidator(1, message='Invalid Credit')])),
                ('capacity', models.IntegerField()),
                ('gender', models.IntegerField(choices=[(0, 'مختلط'), (1, 'مرد'), (2, 'زن')], default=0)),
                ('instructors_list', models.JSONField(blank=True, default=list, null=True)),
                ('times', models.JSONField(default=list)),
                ('exam_time', models.JSONField(blank=True, default=list, null=True)),
                ('description', models.TextField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='accounts.department')),
            ],
        ),
    ]
